//
//  PhotoSceneModels.swift
//  Photolyze
//
//  Created by Mac on 05.09.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreImage

enum PhotoScene {
    
  // MARK: Use cases
  
    enum StoreCall {
        struct Request {
        }
        struct Response {
            let message: String?
        }
        struct ViewModel {
            let alertController: UIAlertController
        }
    }
    
    enum StorePhoto {
        struct Request {
            let image: CIImage?
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
}
