//
//  PhotoScenePresenter.swift
//  Photolyze
//
//  Created by Mac on 05.09.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoScenePresentationLogic {
    func presentSavePhoto(response: PhotoScene.StoreCall.Response)
    func presentStorePhoto(response: PhotoScene.StorePhoto.Response)
}

class PhotoScenePresenter: PhotoScenePresentationLogic {
    weak var viewController: PhotoSceneDisplayLogic?

    // MARK: Do something

    func presentSavePhoto(response: PhotoScene.StoreCall.Response) {
        if let message = response.message {
            
            DispatchQueue.main.async {
                let alert = UIAlertController(title: "Save photo", message: message, preferredStyle: .alert)
                alert.modalPresentationStyle = .overFullScreen
                let action = UIAlertAction(title: "OK", style: .default, handler: nil)
                alert.addAction(action)
                
                let viewModel = PhotoScene.StoreCall.ViewModel(alertController: alert)
                self.viewController?.displaySavePhoto(viewModel: viewModel)
            }
            
           
        }
    }
    
    func presentStorePhoto(response: PhotoScene.StorePhoto.Response) {
        let viewModel = PhotoScene.StorePhoto.ViewModel()
        viewController?.displayStorePhoto(viewModel: viewModel)
    }
    
}
