//
//  PhotoSceneWorker.swift
//  Photolyze
//
//  Created by Mac on 05.09.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhotoSceneWorker {
    
    private let photoAlbum: CustomPhotoAlbum?
    private var weHavePhotoAlbum: Bool = false
    
    init() {
        self.photoAlbum = CustomPhotoAlbum(albumName: Bundle.main.infoDictionary?["CFBundleName"] as! String)
        self.photoAlbum?.prepareAlbum { albumID in
            self.weHavePhotoAlbum = albumID.count > 0
        }
    }
  
    func save(maybeImage: UIImage?, completion: @escaping (String) -> Void) {
        if let image = maybeImage, self.weHavePhotoAlbum {
            self.photoAlbum?.prepareAlbum { _ in
                self.photoAlbum?.saveUImage(image: image, completion: { (message) in
                    completion(message)
                })
            }
        } else {
            completion("We have album = \(weHavePhotoAlbum), we have image = \(maybeImage != nil)")
        }
    }
    
}
