//
//  PhotoSceneConfigurator.swift
//  Photolyze
//
//  Created by Mac on 05.09.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

class PhotoSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = PhotoSceneConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MainSceneViewController) {
        let interactor = PhotoSceneInteractor()
        let presenter = PhotoScenePresenter()
        let router = PhotoSceneRouter()
        let worker = PhotoSceneWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
